version: "3.8"

services:
  app:
    ## O .// 0 "." indica que a imagem do Docker será construida no Diretório atual
    build: .
    command: /bin/sh -c "npm install && npm start"
    ## Mapeia a porta 5000 do conatiner para porta 5000 da máquina
    ports:
      - "5000:5000"
    ## Monta o diretório atual da máquina host no diretório /usr/app dentro do container 
    volumes:
      - .:/usr/app
    ## Indica que o serviço app depende do serviço db
    depends_on:
      - db
  db:
    image: mysql:8.0
    ## Configura o conatiner para reiniciar automaticamente caso ele pare
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: vio_clara
    ## Mapeia a porta 3306 do container para a porta 3306 da máquina
    ports:
      - "3307:3307"
    volumes:
      - db_data:/var/lib/mysql
      - ./mysql-init:/docker-entrypoint-initdb.d

volumes:
  db_data:
